/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseMenu: typeof import('./../../components/menu/base-menu.vue')['default']
    Icon: typeof import('./../../components/Icon/Icon.vue')['default']
    RenderItem: typeof import('./../../components/menu/render-item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenuInline: typeof import('./../../components/menu/sub-menu-inline.vue')['default']
  }
}
